repository: EoinDavey/Setanta
remote_theme: mmistakes/minimal-mistakes@4.18.1
plugins:
    - jekyll-include-cache
title: "Setanta"
name: "Eoin Davey"
site.description: "Doiciméadacht Setanta"
locale: "ga"
url: "docs.try-setanta.ie"
logo: "/assets/images/logo50x50.png"
masthead_title: "Doiciméadacht Setanta"
timezone: "Europe/Dublin"
collections:
    en-docs:
        output: true
        permalink: /:collection/:path
    ga-docs:
        output: true
        permalink: /:collection/:path
    english:
        output: true
        permalink: /:collection/:path
    gaeilge:
        output: true
        permalink: /:collection/:path
defaults:
    # _gaeilge
    - scope:
        path: ""
        type: "gaeilge"
      values:
        sidebar:
            nav: "gaeilge"
    # _english
    - scope:
        path: ""
        type: "english"
      values:
        sidebar:
            nav: "english"

    # _ga-docs
    - scope:
        path: ""
        type: "ga-docs"
      values:
        sidebar:
            nav: "ga-docs"

    # _en-docs
    - scope:
        path: ""
        type: "en-docs"
      values:
        sidebar:
            nav: "en-docs"

include: ["_pages"]
