repository: EoinDavey/Setanta
remote_theme: mmistakes/minimal-mistakes@4.18.1
plugins:
    - jekyll-include-cache
title: "Setanta"
name: "Eoin Davey"
site.description: "Doiciméadacht do Setanta"
locale: "ga"
url: "https://vey.ie/Setanta"
logo: "/assets/images/logo50x50.png"
masthead_title: "Setanta Doiciméadacht"
timezone: "Europe/Dublin"
collections:
    english:
        output: true
        permalink: /:collection/:path
    gaeilge:
        output: true
        permalink: /:collection/:path
defaults:
    # _gaeilge
    - scope:
        path: ""
        type: "gaeilge"
      values:
        sidebar:
            nav: "gaeilge"
    # _english
    - scope:
        path: ""
        type: "english"
      values:
        sidebar:
            nav: "english"


include: ["_pages"]
