name: Node CI/CD

on: [push, pull_request]

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 22.x
      uses: actions/setup-node@v1
      with:
        node-version: '22.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    - run: npm run build
    - run: npm run full-test
    - run: npm publish
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
